# Generated by Django 5.0.6 on 2024-07-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_asignature_teacher_student_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignature',
            name='timeperClass',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
