# Generated by Django 5.0.6 on 2024-07-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_asignature_timeperclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='asignatura',
            new_name='nameAsignature',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='alumno',
            new_name='nameStudent',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='profesor',
            new_name='nameTeacher',
        ),
    ]
