# Generated by Django 5.0.6 on 2024-07-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('0', 'female'), ('1', 'male')], max_length=1)),
                ('dateBth', models.DateTimeField()),
                ('enrolled', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
